version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
