language: node_js
dist: trusty
sudo: required
node_js:
  - stable
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3
install:
  - npm install
script:
  - npm run test
addons:
  chrome: stable